#include<stdio.h>
#include<conio.h>
int main()
{
clrscr();
int a;
char ch;
float ff;
double db;
a=76;
ch='Y';
ff= 7.6;
db= 16.041999;
//printf("Welcome To The World Of C \n");
//printf("Printing all Variables: \n");
printf("The Value of a :  %d \n",a);
printf("The Value of ch: %c \n",ch);
printf("The Value of ff: %f \n",ff);
printf("The Value of db: %e \n",db);
getch();
return 0;
}