#include<stdio.h>
#include<conio.h>
#define BONUS 200.00
#define INITIAL_SALARY 1500.00
#define COMMISION 0.02
int main()
{
clrscr();
char Name;
int Quntity;
float Bonus,Initial_salary,Commision,price;
printf("\n Welcome to iComputers Store ");
printf("\n Name of the Sales Person ",Name);
scanf("%d",&Name);
printf("\n Your's Minimum base Salary",Initial_Salary);
scanf("%f",&Initial_Salary);
print("\n prince of Pc",price);
scanf("%f",&price);
printf("\n NO. of Computers You Sold ",Quntity);
scanf("%f",&n);
Total_
Final_salary=INITIAL_SALARY+BONUS*Quntity+COMMISION;
printf("\n Your's Monthly Salary",Final_salary);
scanf("%f",&Final_salary);
getch();
return 0;
}
